name: Pull Request
on: [pull_request]

jobs:
	Test-deploy:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout branch
				uses: actions/checkout@v2
			- name: Build Custom Image
				run: docker build -t flask:latest .
