name: Test Docker cache
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Build Custom Image
        run: docker build -t flask:latest .
